"""
models_and_kd_v2.py — Model Factory + All KD Baseline Losses

Architectures:
  Teacher : ResNet50-UNet    (~32 M params, ResNet50 encoder)  ← upgraded from ResNet34
  Student : MobileNetV2-UNet (~3.5 M params)                   ← Reverted from ShuffleNetV2
            (ShuffleNetV2 via timm 'tu-shufflenet_v2_x1_0' resulted in a RuntimeError 
            because it is not natively supported in the timm registry).

KD Baselines:
  VanillaKD  — Hinton et al. (2015), soft logit matching
  FitNets    — Romero et al. (2014), intermediate feature L2
  AT         — Zagoruyko & Komodakis (2017), attention map matching

Fix log (v2 → v3):
─────────────────────────────────────────────────────────────────────────────
NEW FIX [Teacher pre-training capability]:
    build_teacher() now accepts a boolean `load_ckpt` flag and will automatically 
    attempt to load the trained checkpoint supplied by `cfg.teacher_ckpt` 
    (or dynamically generated by train.py based on the `seed`). If the teacher
    checkpoint doesn't exist, it prints a loud warning that the teacher is untrained.

Fix 1  [VanillaKD T² loss imbalance]
    OLD: VanillaKDLoss.forward() returned BCE(s, p_t) * T²
         The T² factor (from Hinton 2015) compensates for gradient magnitude
         reduction in *multi-class softmax* distillation.  For binary sigmoid
         segmentation, T²=16 at T=4 inflates the KD term by 16×, completely
         dominating the segmentation loss (observed: total loss ~6.2, never
         converging; val Dice 0.757 < standalone student 0.814).
    FIX: T² multiplier removed from VanillaKDLoss.  Temperature T still
         softens teacher labels; λ_kd alone controls the KD/seg balance.
         cfg.temperature is now 2.0 (was 4.0) as an additional safeguard.
         At T=2 the BCE magnitude (~0.5–0.7) is comparable to SegLoss,
         and λ_kd=0.5 gives a balanced total loss.

AMP safety (carried forward from v2):
    VanillaKDLoss uses F.binary_cross_entropy_with_logits (AMP-safe) not
    F.binary_cross_entropy (AMP-unsafe under torch.autocast float16).
─────────────────────────────────────────────────────────────────────────────
"""

import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import segmentation_models_pytorch as smp
from typing import Dict, Optional, Tuple


# ================================================================
# MODEL FACTORY
# ================================================================
def build_teacher(cfg, load_ckpt=True) -> nn.Module:
    """
    ResNet50-UNet teacher.

    ResNet50 distillation channels (feat_idx=-2):
      encoder.features[-2] = Layer3 → 1024 channels at H/16 × W/16.
    Total params with UNet decoder (256,128,64,32,16): ~32 M.
    """
    model = smp.Unet(
        encoder_name=cfg.teacher_encoder,        # "resnet50"
        encoder_weights=cfg.encoder_weights,     # "imagenet"
        in_channels=3,
        classes=1,
        activation=None,
        decoder_channels=(256, 128, 64, 32, 16),
    )
    model = model.to(cfg.device)

    if load_ckpt:
        ckpt_path = getattr(cfg, 'teacher_ckpt', None)
        if not ckpt_path:
            ckpt_path = os.path.join(cfg.ckpt_dir, f"best_teacher_seed{cfg.seed}.pth")
            if not os.path.exists(ckpt_path):
                ckpt_path = os.path.join(cfg.ckpt_dir, "best_teacher_seed42.pth")
                
        if ckpt_path and os.path.exists(ckpt_path):
            print(f"  [Teacher] Loading weights from {ckpt_path}")
            ckpt = torch.load(ckpt_path, map_location=cfg.device)
            # Support loading standalone teacher models saved via train.py
            model.load_state_dict(ckpt["student"] if "student" in ckpt else ckpt)
        else:
            print(f"  [WARN] Teacher checkpoint not found! Teacher is untrained.")

    return model


def build_student(cfg) -> nn.Module:
    """
    MobileNetV2-UNet student.

    MobileNetV2 distillation channels (feat_idx=-2):
      ~96 channels (auto-detected at runtime in run_method).
    Total params with UNet decoder (128,64,32,16,8): ~3.5 M.
    """
    model = smp.Unet(
        encoder_name=cfg.student_encoder,        # "mobilenet_v2"
        encoder_weights=cfg.encoder_weights,
        in_channels=3,
        classes=1,
        activation=None,
        decoder_channels=(128, 64, 32, 16, 8),
    )
    return model.to(cfg.device)


def get_encoder_feat(
    model: nn.Module,
    x: torch.Tensor,
    feat_idx: int = -2,
) -> Tuple[torch.Tensor, torch.Tensor]:
    """
    Run a forward pass and return (logit, feature_map).

    feat_idx selects which encoder feature level to use for distillation
    (-2 = penultimate encoder block).  Handles both old and new SMP APIs.
    """
    features = model.encoder(x)
    feat_map  = features[feat_idx]

    try:
        decoder_out = model.decoder(*features)
    except TypeError:
        decoder_out = model.decoder(features)

    logit = model.segmentation_head(decoder_out)
    return logit, feat_map


# ================================================================
# SEGMENTATION LOSS (used for all methods)
# ================================================================
class SegLoss(nn.Module):
    """Dice + BCE combined loss (standard for medical segmentation)."""

    def __init__(self, bce_weight: float = 0.5):
        super().__init__()
        self.bce_weight  = bce_weight
        self.dice_weight = 1.0 - bce_weight
        self.bce = nn.BCEWithLogitsLoss()

    def dice_loss(
        self,
        pred_logit: torch.Tensor,
        target: torch.Tensor,
        eps: float = 1e-6,
    ) -> torch.Tensor:
        pred  = torch.sigmoid(pred_logit)
        inter = (pred * target).sum(dim=(1, 2, 3))
        denom = pred.sum(dim=(1, 2, 3)) + target.sum(dim=(1, 2, 3))
        return 1.0 - (2 * inter + eps) / (denom + eps)

    def forward(
        self,
        pred_logit: torch.Tensor,
        target: torch.Tensor,
    ) -> torch.Tensor:
        bce  = self.bce(pred_logit, target)
        dice = self.dice_loss(pred_logit, target).mean()
        return self.bce_weight * bce + self.dice_weight * dice


# ================================================================
# KD BASELINE 1: VANILLA KD (Hinton et al. 2015)
# ================================================================
class VanillaKDLoss(nn.Module):
    """
    Soft-logit knowledge distillation for binary segmentation.

    Temperature T softens the teacher's sigmoid outputs, making the
    soft labels less peaked and transferring more information about
    the relative confidence of each spatial prediction.

    Fix 1 — T² scaling removed
    ───────────────────────────
    Hinton et al. (2015) multiply the KD loss by T² to compensate for
    the 1/T² gradient magnitude reduction that occurs through the softmax
    function in multi-class classification.  For binary segmentation with
    sigmoid, the same gradient attenuation exists, but the absolute loss
    magnitude at initialisation is already comparable to SegLoss (~0.693).
    Multiplying by T² (16 at T=4) inflated the KD term catastrophically,
    dominating the segmentation objective throughout training and yielding
    val Dice 0.757 — worse than the standalone student (0.814).

    The T² factor is therefore removed.  λ_kd is the sole control for
    balancing KD against segmentation.  Temperature is set to T=2.0 in
    Config (default), providing meaningful label softening with T²=4
    providing an acceptable remaining scale difference.

    AMP safety: F.binary_cross_entropy_with_logits is used (not
    F.binary_cross_entropy) because torch.autocast reduces sigmoid outputs
    to float16 while BCE requires float32 inputs.
    """

    def __init__(self, temperature: float = 2.0):
        super().__init__()
        self.T = temperature

    def forward(
        self,
        student_logit: torch.Tensor,
        teacher_logit: torch.Tensor,
    ) -> torch.Tensor:
        B = student_logit.shape[0]
        s = (student_logit / self.T).reshape(B, -1)
        t = (teacher_logit / self.T).reshape(B, -1).detach()

        # Teacher soft labels
        p_t = torch.sigmoid(t)

        # AMP-safe BCE with logits; T² multiplier intentionally absent
        # (see class docstring for full justification).
        loss = F.binary_cross_entropy_with_logits(
            s, p_t.float(), reduction="mean"
        )
        return loss


# ================================================================
# KD BASELINE 2: FitNets (Romero et al. 2014)
# ================================================================
class FitNetsLoss(nn.Module):
    """
    L2 feature matching with a learned linear projector.
    Projects student channels → teacher channels before MSE.
    """

    def __init__(
        self,
        student_channels: int,
        teacher_channels: int,
        device: str = "cpu",
    ):
        super().__init__()
        self.projector = nn.Sequential(
            nn.Conv2d(student_channels, teacher_channels, 1, bias=False),
            nn.BatchNorm2d(teacher_channels),
        ).to(device)

    def forward(
        self,
        feat_s: torch.Tensor,
        feat_t: torch.Tensor,
    ) -> torch.Tensor:
        feat_t = feat_t.detach()
        if feat_s.shape[-2:] != feat_t.shape[-2:]:
            feat_s = F.interpolate(feat_s, size=feat_t.shape[-2:],
                                   mode="bilinear", align_corners=False)
        feat_s_proj = self.projector(feat_s)
        return F.mse_loss(feat_s_proj, feat_t)


# ================================================================
# KD BASELINE 3: Attention Transfer (Zagoruyko & Komodakis, 2017)
# ================================================================
class ATLoss(nn.Module):
    """
    Attention map matching.
    Attention map A(F) = L2-normalised sum of squared channel activations.
    Loss = ‖A(teacher) − A(student)‖₂
    """

    def __init__(self):
        super().__init__()

    @staticmethod
    def attention_map(feat: torch.Tensor) -> torch.Tensor:
        """feat: (B, C, H, W) → attention: (B, 1, H, W), L2-normalised."""
        a      = feat.pow(2).sum(dim=1, keepdim=True)
        a_flat = a.reshape(a.shape[0], -1)
        a_norm = a_flat / (a_flat.norm(dim=1, keepdim=True) + 1e-8)
        return a_norm.reshape_as(a)

    def forward(
        self,
        feat_s: torch.Tensor,
        feat_t: torch.Tensor,
    ) -> torch.Tensor:
        feat_t = feat_t.detach()
        if feat_s.shape[-2:] != feat_t.shape[-2:]:
            feat_s = F.interpolate(feat_s, size=feat_t.shape[-2:],
                                   mode="bilinear", align_corners=False)
        at_t = self.attention_map(feat_t)
        at_s = self.attention_map(feat_s)
        return F.mse_loss(at_s, at_t)


# ================================================================
# KD METHOD REGISTRY
# ================================================================
def build_kd_loss(
    method: str,
    cfg,
    teacher_ch: int,
    student_ch: int,
) -> Optional[nn.Module]:
    """
    Return the KD loss module for the given method name.
    Returns None for 'none' (student trained standalone) and 'teacher'.
    """
    if method in ("none", "teacher"):
        return None

    elif method == "vanilla":
        return VanillaKDLoss(cfg.temperature).to(cfg.device)

    elif method == "fitnets":
        return FitNetsLoss(student_ch, teacher_ch,
                           cfg.device).to(cfg.device)

    elif method == "at":
        return ATLoss().to(cfg.device)

    elif method == "ldl":
        from ldl_layer_v2 import LaguerreDistillationLayer
        return LaguerreDistillationLayer(
            teacher_channels = teacher_ch,
            student_channels = student_ch,
            embed_dim        = cfg.ldl_embed_dim,      # 256 (Fix 4)
            num_anchors      = cfg.ldl_num_anchors,    # 64  (Fix 4)
            alpha            = cfg.ldl_alpha,
            k                = cfg.ldl_k,
            a1               = cfg.ldl_a1,
            b1               = cfg.ldl_b1,
            a2               = cfg.ldl_a2,
            b2               = cfg.ldl_b2,
            T_w              = cfg.ldl_T_w,
            eta0             = cfg.ldl_eta0,
            beta             = cfg.ldl_beta,
            anc_reg          = cfg.ldl_anc_reg,
            anc_reg_tau      = cfg.ldl_anc_reg_tau,
            device           = cfg.device,
        ).to(cfg.device)

    else:
        raise ValueError(f"Unknown KD method: {method!r}")